version: 2
updates:
  - package-ecosystem: docker
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    groups:
      minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    groups:
      minor:
        update-types:
          - minor
          - patch
      hashicorp:
        patterns:
          - hashicorp/*
        update-types:
          - major
