# https://robots.thoughtbot.com/brewfile-a-gemfile-but-for-homebrew

brew 'bash-completion'
brew 'ffmpeg'
brew 'gcc'
brew 'git'
brew 'grc'
brew 'htop'
brew 'nmap'
brew 'openssl'
brew 'ssh-copy-id'
brew 'the_silver_searcher'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'youtube-dl'
