---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.13'
      - uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7 # v1.6.1
        id: vim
      - run: make install-vint lint
        env:
          VIM_EXE: ${{ steps.vim.outputs.executable }}

  test:
    strategy:
      fail-fast: false
      matrix:
        vim:
          - version: stable
            neovim: false
          - version: v8.2.0000
            neovim: false
          - version: stable
            neovim: true

    name: "test (${{ matrix.vim.neovim && 'neovim' || 'vim' }} ${{ matrix.vim.version }})"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7 # v1.6.1
        id: vim
        with:
          neovim: ${{ matrix.vim.neovim }}
          version: ${{ matrix.vim.version }}
      - run: make test
        env:
          VIM_EXE: ${{ steps.vim.outputs.executable }}
