# include .bashrc if it exists
if [ -f ~/.bashrc ]; then
   . ~/.bashrc
fi

# vim: set filetype=sh:

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
