## Handy file for aliases, keep them seperate you here?

# Write vim log to disk
# http://www.drbunsen.org/vim-croquet/
alias vim='vim -w ~/.vimlog "$@"'

## enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    #eval "dircolors -b"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

## some more ls aliases
alias ll='ls -lh'
alias lt='ls -lth'
alias la='ls -A'
alias l='ls -CF'

pidof () { ps -Acw | egrep -i $@ | awk '{print $1}'; }

# Job Stuff
alias h='history'
alias j="jobs -l"

# Directory jumping
alias pu="pushd"
alias po="popd"

## duh
alias motd="cat /etc/motd"

# For epic typing fail
alias bim="vim"
alias cim="vim"
alias vi='vim'

# pgp.io
alias pgpio="~/Projects/pgpio/pgpio"

# Csh compatability:
alias unsetenv=unset
function setenv () {
  export $1="$2"
}

# free env
dotenv () {
  set -a
  [ -f .env ] && . .env
  set +a
}

alias fuck='sudo $(history -p \!\!)'

function aws_session() {
  local profile=campaign-billing
  local username=$(aws iam get-user --profile=$profile --query User.UserName --output text)
  local device=$(aws iam list-mfa-devices --profile=$profile --user-name $username --query MFADevices[0].SerialNumber --output text)
  echo -n "Authentication code for ${device} (${profile}/${username}): "

  local code
  read code

  local sts=$(aws sts get-session-token --profile=$profile --duration-seconds 3600 --serial-number $device --token-code $code --output text)

  export AWS_ACCESS_KEY_ID=$(echo "$sts" | cut -f 2)
  export AWS_SECRET_ACCESS_KEY=$(echo "$sts" | cut -f 4)
  export AWS_SESSION_TOKEN=$(echo "$sts" | cut -f 5)
}

# vim: set filetype=sh:
