# include .bashrc if it exists
if [ -f ~/.bashrc ]; then
   . ~/.bashrc
fi

# vim: set filetype=sh:

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
