""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" .vimrc -- the way it ought to be: Ha. It rhymes!
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Basics
set encoding=utf-8
behave xterm
set nocompatible       " no compatibility with vi
filetype on            " recognize syntax by file extension
filetype plugin on     " Look at .vim/ftplugin
filetype indent on     " check for indent file
syntax on              " syntax highlighting

execute pathogen#infect()

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

set ai " Auto indent

set backspace=2        " allow <BS> to go past last insert
set gdefault           " assume :s uses /g
set ignorecase         " ignore case in search patterns
set smartcase          " searches are case-sensitive if caps used
set incsearch          " immediately highlight search matches
set noerrorbells       " no beeps on errors
set nomodeline         " prevent others from overriding this .vimrc
set number             " display line numbers
set ruler              " display row, column and % of document
set showcmd            " show partial commands in the status line
set showmatch          " show matching () {} etc.
set showmode           " show current mode
set hidden             " Allow for hidden buffers

set spellfile=$HOME/.vim/spell/en.utf-8.add

"set tw=100            " When you type gq to wrap a paragraph, wrap to 100 characters.

" Creates unlimited undos
set undofile
set undodir=~/.vim/undodir

" Settings for autoindentation, comments, and what-have-you
set expandtab          " expand tabs with spaces
set tabstop=2          " <Tab> move three characters
set shiftwidth=2       " >> and << shift 3 spaces
"set textwidth=79       " hard wrap at 79 characters
set modeline           " check for a modeline
set softtabstop=2      " see spaces as tabs
set scrolloff=5        " start scrolling when cursor is N lines from edge

" whoa... wtf?
set nowrap             " don't soft wrap
set wrap               " linewrap

" turns status line always on and configures it
set laststatus=2
set statusline=%<%f\ %m\ %h%r%=%b\ 0x%B\ \ %l,%c%V\ %P\ of\ %L

" Puts swapfiles in /tmp instead of current directory.
set directory=/tmp

" For work stuff
if filereadable("/usr/share/vim/google/google.vim")
  source /usr/share/vim/google/google.vim
endif

" FZF
if filereadable("/usr/share/doc/fzf/examples/fzf.vim")
  source /usr/share/doc/fzf/examples/fzf.vim
  nnoremap ff :Files<CR>
endif

if filereadable("/opt/homebrew/opt/fzf/plugin/fzf.vim")
  " set rtp+=$HOMEBREW_PREFIX/opt/fzf
  source /opt/homebrew/opt/fzf/plugin/fzf.vim
  nnoremap ff :Files<CR>
endif

" Enables scrolling in vim
set mouse=a
if has("mouse_sgr")
  set ttymouse=sgr
else
  set ttymouse=xterm2
end

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Color Stuff

syntax enable
colorscheme darknat

" Highlights long lines (Turned off...)
"highlight OverLength term=standout cterm=bold ctermfg=1
"match OverLength /\%80v.\+/

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" One off prject stuff
autocmd BufNewFile,BufRead ~/Projects/apom/* set tabstop=3 shiftwidth=3 softtabstop=3

nmap <Leader>t :TagbarToggle<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Extra Language Support

" Antlr
au BufRead,BufNewFile *.g set ft=antlr

" Less
au BufRead,BufNewFile *.less set ft=less

" Markdown
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_strikethrough = 1

au BufRead,BufNewFile *.md set ft=markdown

" Makefiles
au BufRead,BufNewFile [Mm]akefile* set noet ts=8 sw=8 nocindent list lcs=tab:>-,trail:x

" F#
au BufRead,BufNewFile *.fs set ft=fs

" tsx https://github.com/peitalin/vim-jsx-typescript
autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescriptreact

" ALE + Js
let g:ale_fixers = {
      \  'javascript': ['eslint'],
      \  'typescript': ['eslint'],
      \  'graphql': ['eslint'],
      \}
let g:ale_fix_on_save = 1

" Text Files
"au BufRead,BufNewFile *.txt highlight clear OverLength
"au BufRead,BufNewFile *.txt set textwidth=80

" God
au BufRead,BufNewFile *.god set filetype=ruby

" Tex Files
au BufRead,BufNewFile *.tex highlight clear OverLength
au BufRead,BufNewFile *.bib highlight clear OverLength

" Tab Seperated Files
au BufRead,BufNewFile *.tsv set noet

" Proto buffers?
au BufRead,BufNewFile *.proto set ft=proto

" Python Templates
au BufRead,BufNewFile *.dtl set ft=htmldjango
au BufRead,BufNewFile *.template set ft=htmldjango

" Go Templates
au BufRead,BufNewFile *.tpl set ft=gotplhtml

" Go Lint
set rtp+=$GOPATH/src/github.com/golang/lint/misc/vim

" Go Fmt
au BufWritePre,FileWritePre *.go :GoFmt

" JSON Fmt
autocmd FileType json autocmd BufWritePre <buffer> %!jq .

" Turn on terraform auto fmt
let g:terraform_fmt_on_save=1
let g:terraform_align=0

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Key Bindings

" Remove trailing spaces from lines w/ F6:
" http://vim.wikia.com/wiki/Remove_unwanted_spaces
:nnoremap <Leader>l :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

" Shawn's code was cool, but this works on all vcs'
:nnoremap <Leader>b :VCSBlame<CR>

" Because we like our line numbers sometimes...
:nnoremap <Leader>n :set invnumber<CR>

" But we don't always wanna wrap
:nnoremap <Leader>r :set invwrap<CR>

" And all the cool kids need to paste
:nnoremap <Leader>p :set invpaste<CR>

" Use the space key to open and close code folds
:vnoremap <space> zf<CR>
:nnoremap <space> zd<CR>

" Toggle spell checking.
:map <Leader>7 :set spell!<cr>

" Clear search buffer with Ctrl+l
:noremap <silent> <c-l> :nohls<cr><c-l>

" Buffer navigation shortcuts
:nnoremap <Leader>w <c-w><Up><CR>
:nnoremap <Leader>s <c-w><Down><CR>
:nnoremap <Leader>a <c-w><Left><CR>
:nnoremap <Leader>d <c-w><Right><CR>

" Copilot settings
let g:copilot_workspace_folders = ["~/Projects/", "~/Work/"]
let g:copilot_filetypes = { 'typst': v:false, }
