DISABLE_AUTO_UPDATE="true"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

export HOMEBREW_NO_ENV_HINTS=1

export VIRTUAL_ENV_DISABLE_PROMPT=1
[[ -d "/opt/homebrew/bin" ]] && export PATH="/opt/homebrew/bin:$PATH"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="icco"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

CASE_SENSITIVE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  dotenv
  shrink-path
  iterm2
  zoxide
  macos
  git-prompt
)

zstyle :omz:plugins:iterm2 shell-integration yes

# Must precede oh-my-zsh.sh: omz runs compinit, and it can only pick up
# brew's site-functions if they're already on FPATH. Probe the known prefixes
# in order rather than shelling out to `brew --prefix`, and stop at the first
# hit so we keep the single-prefix behaviour this replaced. Linux hosts use
# the linuxbrew path; hosts without brew match nothing.
() {
  local d
  for d in /opt/homebrew /usr/local /home/linuxbrew/.linuxbrew; do
    if [[ -d $d/share/zsh/site-functions ]]; then
      FPATH=$d/share/zsh/site-functions:$FPATH
      break
    fi
  done
}

source $ZSH/oh-my-zsh.sh

# User configuration
export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

export GOPROXY="https://proxy.golang.org"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$GOPATH/bin:$PATH"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# vim: set filetype=zsh:
